### ISSUE TITLE
Backend breaks sigma-cli

### ISSUE THREAD

**Issue by seanthegeek** [AttackIQ/pySigma-backend-microsoft365defender#3]
After installing the backend, and singma command fails

After installing the backend, and singma command fails

After installing the backend, and singma command fails

After installing the backend, and sigma command fails

```text
Traceback (most recent call last):
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/processing/transformations.py", line 473, in __post_init__
    self.re = re.compile(self.regex)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 863, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sean/.local/bin/sigma", line 5, in <module>
    from sigma.cli.main import main
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/cli/main.py", line 3, in <module>
    from .list import list_group
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/cli/list.py", line 6, in <module>
    plugins = InstalledSigmaPlugins.autodiscover()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/plugins.py", line 65, in autodiscover
    backends = cls._discover_module_directories(sigma.backends, "backends", include_backends)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/plugins.py", line 53, in _discover_module_directories
    imported_module = importlib.import_module(module.name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/backends/microsoft365defender/__init__.py", line 1, in <module>
    from .microsoft365defender import Microsoft365DefenderBackend
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/backends/microsoft365defender/microsoft365defender.py", line 8, in <module>
    from sigma.pipelines.microsoft365defender import microsoft_365_defender_pipeline
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/pipelines/microsoft365defender/__init__.py", line 1, in <module>
    from .microsoft365defender import microsoft_365_defender_pipeline
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/pipelines/microsoft365defender/microsoft365defender.py", line 419, in <module>
    transformation=ReplaceStringTransformation(regex=r"((?i)^HKLM\\SYSTEM\\CurrentControlSet)",
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 5, in __init__
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/processing/transformations.py", line 475, in __post_init__
    raise SigmaRegularExpressionError(f"Regular expression '{self.regex}' is invalid: {str(e)}") from e
sigma.exceptions.SigmaRegularExpressionError: Regular expression '((?i)^HKLM\\SYSTEM\\CurrentControlSet)' is invalid: global flags not at the start of the expression at position 1
```

**Comment by slincoln-aiq** [comment]
Hi @seanthegeek , thanks for reporting this. 

This has been fixed in the latest release. Let me know if you have any other issues. Thanks!
